### ISSUE TITLE
在koishi desktop上安装此插件所需的puppeteer依赖并重启，会导致koishi desktop 出现白屏not found问题

### ISSUE THREAD

**Issue by KiriSuoh** [Mahoo12138/koishi-plugin-douban#1]
重装koishi并把插件挨个排查之后发现此问题。

douban插件需要的依赖puppeteer明明已经安装了3.5版本，插件设置页仍显示缺少puppeteer依赖，点进这个提示安装了3.2版本的puppeteer后仍提示缺乏依赖，之后重启koishi便可复现此问题。会导致整个koishi无法使用。

白屏 not found 问题和论坛该贴所说一致：
https://forum.koishi.xyz/t/topic/278/3

插件版本0.2.2
koishi版本如下：
System:
    OS: Windows 10 10.0.20348
    CPU: (2) x64 Intel(R) Xeon(R) CPU E5-2682 v4 @ 2.50GHz

Binaries:
    Node: 16.19.1
    Yarn: 3.5.0

Koishi:
    Core: 4.14.5
    Console: 5.14.2
    Koishi Desktop: 0.10.6

**Comment by Mahoo12138** [comment]
会不会是 puppeteer 的问题，我本地没有复现出来
